spring:
  application:
    name: ms-repo-user

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:defaultUser@example.com}
    password: ${MAIL_PASSWORD:defaultPassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  servlet:
    context-path: /ms-repo-user
  port: 54430

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://host.docker.internal:8761/eureka/