server:
  servlet:
    context-path: /ms-users
  port: 0

spring:
  application:
    name: ms-users

  datasource:
    url: jdbc:mysql://localhost:3309/bd_drink
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # O "validate", "create", etc.
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

    # (Opcional) Timezone handling for MySQL
    jackson:
    time-zone: UTC

# (Opcional) Logging de SQL
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    ##Se registra con el nombre y el puerto en eureka server
    ##prefer-ip-address: true