server:
  servlet:
    context-path: /ms-users
  port: 0

spring:
  application:
    name: ms-users

  #Es para indicar cual archivo de GIT va a leer
  profiles:
    active: dev
  #Es la ruta para leer las configuraciones en git
  config:
    import: "optional:configserver:http://localhost:7777"

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  #Es para indicar cual archivo de GIT va a leer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    ##Se registra con el nombre y el puerto en eureka server
    ##prefer-ip-address: true